### ISSUE TITLE
Configuration: Set up dev containers in Dockers

### ISSUE THREAD

**Issue by ciminibb** [EECE3093C/team-project-the-over-under#44]
Goal:
Create docker container of front end application from docker image.

Resources: 
https://docs.docker.com/engine/reference/builder/

Deliverables:
N/A

**Comment by mckettja** [comment]
Since switch to Express.js framework, redesigned Dockerfile to open using node, instead of Ubuntu. Way too much time spent on getting Ubuntu working.
