### ISSUE TITLE
Testing: Write unit test for parsers in Python

### ISSUE THREAD

**Issue by ciminibb** [EECE3093C/team-project-the-over-under#91]
Target:
Validate the data returned by the parsers on form and completeness.

Deliverable:
test_SportsbookParsers.py

**Comment by mckettja** [comment]
structure put in 90-91-92-python-unit-test branch

**Comment by mckettja** [comment]
debugging issues with import causing issues. python is not locating 'Classes' directory and is effecting all parsers  as well as unit test @EECE3093C/the-over-under
